export interface Department {
  code: string;
  name: string;
  prefecture: string;
  region: string;
  sousPrefectures: string[];
  notoriety: number; // 1 = very famous, 6 = obscure
}

export const DEPARTMENTS: Department[] = [
  { code: "01", name: "Ain", prefecture: "Bourg-en-Bresse", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Belley", "Gex", "Nantua"], notoriety: 3 },
  { code: "02", name: "Aisne", prefecture: "Laon", region: "Hauts-de-France", sousPrefectures: ["Château-Thierry", "Saint-Quentin", "Soissons", "Vervins"], notoriety: 4 },
  { code: "03", name: "Allier", prefecture: "Moulins", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Montluçon", "Vichy"], notoriety: 4 },
  { code: "04", name: "Alpes-de-Haute-Provence", prefecture: "Digne-les-Bains", region: "Provence-Alpes-Côte d'Azur", sousPrefectures: ["Barcelonnette", "Castellane", "Forcalquier"], notoriety: 5 },
  { code: "05", name: "Hautes-Alpes", prefecture: "Gap", region: "Provence-Alpes-Côte d'Azur", sousPrefectures: ["Briançon"], notoriety: 5 },
  { code: "06", name: "Alpes-Maritimes", prefecture: "Nice", region: "Provence-Alpes-Côte d'Azur", sousPrefectures: ["Grasse"], notoriety: 1 },
  { code: "07", name: "Ardèche", prefecture: "Privas", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Largentière", "Tournon-sur-Rhône"], notoriety: 4 },
  { code: "08", name: "Ardennes", prefecture: "Charleville-Mézières", region: "Grand Est", sousPrefectures: ["Rethel", "Sedan", "Vouziers"], notoriety: 4 },
  { code: "09", name: "Ariège", prefecture: "Foix", region: "Occitanie", sousPrefectures: ["Pamiers", "Saint-Girons"], notoriety: 5 },
  { code: "10", name: "Aube", prefecture: "Troyes", region: "Grand Est", sousPrefectures: ["Bar-sur-Aube", "Nogent-sur-Seine"], notoriety: 4 },
  { code: "11", name: "Aude", prefecture: "Carcassonne", region: "Occitanie", sousPrefectures: ["Limoux", "Narbonne"], notoriety: 3 },
  { code: "12", name: "Aveyron", prefecture: "Rodez", region: "Occitanie", sousPrefectures: ["Millau", "Villefranche-de-Rouergue"], notoriety: 4 },
  { code: "13", name: "Bouches-du-Rhône", prefecture: "Marseille", region: "Provence-Alpes-Côte d'Azur", sousPrefectures: ["Aix-en-Provence", "Arles", "Istres"], notoriety: 1 },
  { code: "14", name: "Calvados", prefecture: "Caen", region: "Normandie", sousPrefectures: ["Bayeux", "Lisieux", "Vire"], notoriety: 3 },
  { code: "15", name: "Cantal", prefecture: "Aurillac", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Mauriac", "Saint-Flour"], notoriety: 5 },
  { code: "16", name: "Charente", prefecture: "Angoulême", region: "Nouvelle-Aquitaine", sousPrefectures: ["Cognac", "Confolens"], notoriety: 4 },
  { code: "17", name: "Charente-Maritime", prefecture: "La Rochelle", region: "Nouvelle-Aquitaine", sousPrefectures: ["Jonzac", "Rochefort", "Saintes"], notoriety: 3 },
  { code: "18", name: "Cher", prefecture: "Bourges", region: "Centre-Val de Loire", sousPrefectures: ["Saint-Amand-Montrond", "Vierzon"], notoriety: 4 },
  { code: "19", name: "Corrèze", prefecture: "Tulle", region: "Nouvelle-Aquitaine", sousPrefectures: ["Brive-la-Gaillarde", "Ussel"], notoriety: 4 },
  { code: "21", name: "Côte-d'Or", prefecture: "Dijon", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Beaune", "Montbard"], notoriety: 2 },
  { code: "22", name: "Côtes-d'Armor", prefecture: "Saint-Brieuc", region: "Bretagne", sousPrefectures: ["Dinan", "Guingamp", "Lannion"], notoriety: 4 },
  { code: "23", name: "Creuse", prefecture: "Guéret", region: "Nouvelle-Aquitaine", sousPrefectures: ["Aubusson"], notoriety: 5 },
  { code: "24", name: "Dordogne", prefecture: "Périgueux", region: "Nouvelle-Aquitaine", sousPrefectures: ["Bergerac", "Nontron", "Sarlat-la-Canéda"], notoriety: 3 },
  { code: "25", name: "Doubs", prefecture: "Besançon", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Montbéliard", "Pontarlier"], notoriety: 3 },
  { code: "26", name: "Drôme", prefecture: "Valence", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Die", "Nyons"], notoriety: 3 },
  { code: "27", name: "Eure", prefecture: "Évreux", region: "Normandie", sousPrefectures: ["Bernay", "Les Andelys", "Vernon"], notoriety: 4 },
  { code: "28", name: "Eure-et-Loir", prefecture: "Chartres", region: "Centre-Val de Loire", sousPrefectures: ["Châteaudun", "Dreux", "Nogent-le-Rotrou"], notoriety: 4 },
  { code: "29", name: "Finistère", prefecture: "Quimper", region: "Bretagne", sousPrefectures: ["Brest", "Châteaulin", "Morlaix"], notoriety: 3 },
  { code: "2A", name: "Corse-du-Sud", prefecture: "Ajaccio", region: "Corse", sousPrefectures: ["Porto-Vecchio", "Sartène"], notoriety: 3 },
  { code: "2B", name: "Haute-Corse", prefecture: "Bastia", region: "Corse", sousPrefectures: ["Calvi", "Corte"], notoriety: 4 },
  { code: "30", name: "Gard", prefecture: "Nîmes", region: "Occitanie", sousPrefectures: ["Alès", "Le Vigan"], notoriety: 2 },
  { code: "31", name: "Haute-Garonne", prefecture: "Toulouse", region: "Occitanie", sousPrefectures: ["Muret", "Saint-Gaudens"], notoriety: 1 },
  { code: "32", name: "Gers", prefecture: "Auch", region: "Occitanie", sousPrefectures: ["Condom", "Mirande"], notoriety: 5 },
  { code: "33", name: "Gironde", prefecture: "Bordeaux", region: "Nouvelle-Aquitaine", sousPrefectures: ["Arcachon", "Blaye", "Langon", "Lesparre-Médoc"], notoriety: 1 },
  { code: "34", name: "Hérault", prefecture: "Montpellier", region: "Occitanie", sousPrefectures: ["Béziers", "Lodève"], notoriety: 2 },
  { code: "35", name: "Ille-et-Vilaine", prefecture: "Rennes", region: "Bretagne", sousPrefectures: ["Fougères", "Redon", "Saint-Malo"], notoriety: 2 },
  { code: "36", name: "Indre", prefecture: "Châteauroux", region: "Centre-Val de Loire", sousPrefectures: ["Le Blanc", "La Châtre", "Issoudun"], notoriety: 5 },
  { code: "37", name: "Indre-et-Loire", prefecture: "Tours", region: "Centre-Val de Loire", sousPrefectures: ["Chinon", "Loches"], notoriety: 2 },
  { code: "38", name: "Isère", prefecture: "Grenoble", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["La Tour-du-Pin", "Vienne"], notoriety: 2 },
  { code: "39", name: "Jura", prefecture: "Lons-le-Saunier", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Dole", "Saint-Claude"], notoriety: 4 },
  { code: "40", name: "Landes", prefecture: "Mont-de-Marsan", region: "Nouvelle-Aquitaine", sousPrefectures: ["Dax"], notoriety: 4 },
  { code: "41", name: "Loir-et-Cher", prefecture: "Blois", region: "Centre-Val de Loire", sousPrefectures: ["Romorantin-Lanthenay", "Vendôme"], notoriety: 4 },
  { code: "42", name: "Loire", prefecture: "Saint-Étienne", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Montbrison", "Roanne"], notoriety: 2 },
  { code: "43", name: "Haute-Loire", prefecture: "Le Puy-en-Velay", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Brioude", "Yssingeaux"], notoriety: 4 },
  { code: "44", name: "Loire-Atlantique", prefecture: "Nantes", region: "Pays de la Loire", sousPrefectures: ["Ancenis", "Châteaubriant", "Saint-Nazaire"], notoriety: 1 },
  { code: "45", name: "Loiret", prefecture: "Orléans", region: "Centre-Val de Loire", sousPrefectures: ["Montargis", "Pithiviers"], notoriety: 2 },
  { code: "46", name: "Lot", prefecture: "Cahors", region: "Occitanie", sousPrefectures: ["Figeac", "Gourdon"], notoriety: 4 },
  { code: "47", name: "Lot-et-Garonne", prefecture: "Agen", region: "Nouvelle-Aquitaine", sousPrefectures: ["Marmande", "Nérac", "Villeneuve-sur-Lot"], notoriety: 4 },
  { code: "48", name: "Lozère", prefecture: "Mende", region: "Occitanie", sousPrefectures: ["Florac"], notoriety: 5 },
  { code: "49", name: "Maine-et-Loire", prefecture: "Angers", region: "Pays de la Loire", sousPrefectures: ["Cholet", "Saumur", "Segré"], notoriety: 2 },
  { code: "50", name: "Manche", prefecture: "Saint-Lô", region: "Normandie", sousPrefectures: ["Avranches", "Cherbourg-en-Cotentin", "Coutances"], notoriety: 4 },
  { code: "51", name: "Marne", prefecture: "Châlons-en-Champagne", region: "Grand Est", sousPrefectures: ["Épernay", "Reims", "Sainte-Menehould", "Vitry-le-François"], notoriety: 3 },
  { code: "52", name: "Haute-Marne", prefecture: "Chaumont", region: "Grand Est", sousPrefectures: ["Langres", "Saint-Dizier"], notoriety: 5 },
  { code: "53", name: "Mayenne", prefecture: "Laval", region: "Pays de la Loire", sousPrefectures: ["Château-Gontier", "Mayenne"], notoriety: 4 },
  { code: "54", name: "Meurthe-et-Moselle", prefecture: "Nancy", region: "Grand Est", sousPrefectures: ["Briey", "Lunéville", "Toul"], notoriety: 2 },
  { code: "55", name: "Meuse", prefecture: "Bar-le-Duc", region: "Grand Est", sousPrefectures: ["Commercy", "Verdun"], notoriety: 5 },
  { code: "56", name: "Morbihan", prefecture: "Vannes", region: "Bretagne", sousPrefectures: ["Lorient", "Pontivy"], notoriety: 3 },
  { code: "57", name: "Moselle", prefecture: "Metz", region: "Grand Est", sousPrefectures: ["Forbach", "Sarrebourg", "Sarreguemines", "Thionville"], notoriety: 2 },
  { code: "58", name: "Nièvre", prefecture: "Nevers", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Château-Chinon", "Clamecy", "Cosne-Cours-sur-Loire"], notoriety: 5 },
  { code: "59", name: "Nord", prefecture: "Lille", region: "Hauts-de-France", sousPrefectures: ["Avesnes-sur-Helpe", "Cambrai", "Douai", "Dunkerque", "Valenciennes"], notoriety: 1 },
  { code: "60", name: "Oise", prefecture: "Beauvais", region: "Hauts-de-France", sousPrefectures: ["Clermont", "Compiègne", "Senlis"], notoriety: 3 },
  { code: "61", name: "Orne", prefecture: "Alençon", region: "Normandie", sousPrefectures: ["Argentan", "Mortagne-au-Perche"], notoriety: 5 },
  { code: "62", name: "Pas-de-Calais", prefecture: "Arras", region: "Hauts-de-France", sousPrefectures: ["Béthune", "Boulogne-sur-Mer", "Calais", "Lens", "Montreuil", "Saint-Omer"], notoriety: 2 },
  { code: "63", name: "Puy-de-Dôme", prefecture: "Clermont-Ferrand", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Ambert", "Issoire", "Riom", "Thiers"], notoriety: 2 },
  { code: "64", name: "Pyrénées-Atlantiques", prefecture: "Pau", region: "Nouvelle-Aquitaine", sousPrefectures: ["Bayonne", "Oloron-Sainte-Marie"], notoriety: 3 },
  { code: "65", name: "Hautes-Pyrénées", prefecture: "Tarbes", region: "Occitanie", sousPrefectures: ["Argelès-Gazost", "Bagnères-de-Bigorre"], notoriety: 4 },
  { code: "66", name: "Pyrénées-Orientales", prefecture: "Perpignan", region: "Occitanie", sousPrefectures: ["Céret", "Prades"], notoriety: 3 },
  { code: "67", name: "Bas-Rhin", prefecture: "Strasbourg", region: "Grand Est", sousPrefectures: ["Haguenau", "Molsheim", "Saverne", "Sélestat"], notoriety: 2 },
  { code: "68", name: "Haut-Rhin", prefecture: "Colmar", region: "Grand Est", sousPrefectures: ["Altkirch", "Mulhouse", "Thann"], notoriety: 2 },
  { code: "69", name: "Rhône", prefecture: "Lyon", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Villefranche-sur-Saône"], notoriety: 1 },
  { code: "70", name: "Haute-Saône", prefecture: "Vesoul", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Lure"], notoriety: 5 },
  { code: "71", name: "Saône-et-Loire", prefecture: "Mâcon", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Autun", "Chalon-sur-Saône", "Charolles", "Louhans"], notoriety: 3 },
  { code: "72", name: "Sarthe", prefecture: "Le Mans", region: "Pays de la Loire", sousPrefectures: ["La Flèche", "Mamers"], notoriety: 3 },
  { code: "73", name: "Savoie", prefecture: "Chambéry", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Albertville", "Saint-Jean-de-Maurienne"], notoriety: 3 },
  { code: "74", name: "Haute-Savoie", prefecture: "Annecy", region: "Auvergne-Rhône-Alpes", sousPrefectures: ["Bonneville", "Saint-Julien-en-Genevois", "Thonon-les-Bains"], notoriety: 2 },
  { code: "75", name: "Paris", prefecture: "Paris", region: "Île-de-France", sousPrefectures: [], notoriety: 1 },
  { code: "76", name: "Seine-Maritime", prefecture: "Rouen", region: "Normandie", sousPrefectures: ["Dieppe", "Le Havre"], notoriety: 2 },
  { code: "77", name: "Seine-et-Marne", prefecture: "Melun", region: "Île-de-France", sousPrefectures: ["Fontainebleau", "Meaux", "Provins", "Torcy"], notoriety: 3 },
  { code: "78", name: "Yvelines", prefecture: "Versailles", region: "Île-de-France", sousPrefectures: ["Mantes-la-Jolie", "Rambouillet", "Saint-Germain-en-Laye"], notoriety: 2 },
  { code: "79", name: "Deux-Sèvres", prefecture: "Niort", region: "Nouvelle-Aquitaine", sousPrefectures: ["Bressuire", "Parthenay"], notoriety: 4 },
  { code: "80", name: "Somme", prefecture: "Amiens", region: "Hauts-de-France", sousPrefectures: ["Abbeville", "Montdidier", "Péronne"], notoriety: 3 },
  { code: "81", name: "Tarn", prefecture: "Albi", region: "Occitanie", sousPrefectures: ["Castres"], notoriety: 4 },
  { code: "82", name: "Tarn-et-Garonne", prefecture: "Montauban", region: "Occitanie", sousPrefectures: ["Castelsarrasin"], notoriety: 4 },
  { code: "83", name: "Var", prefecture: "Toulon", region: "Provence-Alpes-Côte d'Azur", sousPrefectures: ["Brignoles", "Draguignan"], notoriety: 2 },
  { code: "84", name: "Vaucluse", prefecture: "Avignon", region: "Provence-Alpes-Côte d'Azur", sousPrefectures: ["Apt", "Carpentras"], notoriety: 3 },
  { code: "85", name: "Vendée", prefecture: "La Roche-sur-Yon", region: "Pays de la Loire", sousPrefectures: ["Fontenay-le-Comte", "Les Sables-d'Olonne"], notoriety: 3 },
  { code: "86", name: "Vienne", prefecture: "Poitiers", region: "Nouvelle-Aquitaine", sousPrefectures: ["Châtellerault", "Montmorillon"], notoriety: 3 },
  { code: "87", name: "Haute-Vienne", prefecture: "Limoges", region: "Nouvelle-Aquitaine", sousPrefectures: ["Bellac", "Rochechouart"], notoriety: 3 },
  { code: "88", name: "Vosges", prefecture: "Épinal", region: "Grand Est", sousPrefectures: ["Neufchâteau", "Saint-Dié-des-Vosges"], notoriety: 4 },
  { code: "89", name: "Yonne", prefecture: "Auxerre", region: "Bourgogne-Franche-Comté", sousPrefectures: ["Avallon", "Sens"], notoriety: 4 },
  { code: "90", name: "Territoire de Belfort", prefecture: "Belfort", region: "Bourgogne-Franche-Comté", sousPrefectures: [], notoriety: 4 },
  { code: "91", name: "Essonne", prefecture: "Évry-Courcouronnes", region: "Île-de-France", sousPrefectures: ["Étampes", "Palaiseau"], notoriety: 3 },
  { code: "92", name: "Hauts-de-Seine", prefecture: "Nanterre", region: "Île-de-France", sousPrefectures: ["Antony", "Boulogne-Billancourt"], notoriety: 2 },
  { code: "93", name: "Seine-Saint-Denis", prefecture: "Bobigny", region: "Île-de-France", sousPrefectures: ["Le Raincy", "Saint-Denis"], notoriety: 2 },
  { code: "94", name: "Val-de-Marne", prefecture: "Créteil", region: "Île-de-France", sousPrefectures: ["L'Haÿ-les-Roses", "Nogent-sur-Marne"], notoriety: 2 },
  { code: "95", name: "Val-d'Oise", prefecture: "Pontoise", region: "Île-de-France", sousPrefectures: ["Argenteuil", "Sarcelles"], notoriety: 3 },
  { code: "971", name: "Guadeloupe", prefecture: "Basse-Terre", region: "Guadeloupe", sousPrefectures: ["Pointe-à-Pitre"], notoriety: 4 },
  { code: "972", name: "Martinique", prefecture: "Fort-de-France", region: "Martinique", sousPrefectures: ["La Trinité", "Le Marin"], notoriety: 4 },
  { code: "973", name: "Guyane", prefecture: "Cayenne", region: "Guyane", sousPrefectures: ["Saint-Laurent-du-Maroni"], notoriety: 5 },
  { code: "974", name: "La Réunion", prefecture: "Saint-Denis", region: "La Réunion", sousPrefectures: ["Saint-Benoît", "Saint-Paul", "Saint-Pierre"], notoriety: 4 },
  { code: "976", name: "Mayotte", prefecture: "Mamoudzou", region: "Mayotte", sousPrefectures: [], notoriety: 5 },
];

export const REGIONS = [
  "Auvergne-Rhône-Alpes",
  "Bourgogne-Franche-Comté",
  "Bretagne",
  "Centre-Val de Loire",
  "Corse",
  "Grand Est",
  "Guadeloupe",
  "Guyane",
  "Hauts-de-France",
  "Île-de-France",
  "La Réunion",
  "Martinique",
  "Mayotte",
  "Normandie",
  "Nouvelle-Aquitaine",
  "Occitanie",
  "Pays de la Loire",
  "Provence-Alpes-Côte d'Azur",
];
