export interface ExpertQuestion {
  text: string;
  accepted_answers: string[];
  display_answer: string;
  difficulty: 5 | 6;
}

export const EXPERT_QUESTIONS: ExpertQuestion[] = [
  // Difficulty 5 — challenging
  {
    text: "Quelle est la sous-préfecture la plus au nord du département de l'Ain ?",
    accepted_answers: ["Gex"],
    display_answer: "Gex",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Cahors ?",
    accepted_answers: ["Lot"],
    display_answer: "Lot",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Mende ?",
    accepted_answers: ["Lot"],
    display_answer: "Lot",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Albi ?",
    accepted_answers: ["Tarn"],
    display_answer: "Tarn",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Orléans ?",
    accepted_answers: ["Loire"],
    display_answer: "Loire",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Rouen ?",
    accepted_answers: ["Seine"],
    display_answer: "Seine",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Besançon ?",
    accepted_answers: ["Doubs"],
    display_answer: "Doubs",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Metz ?",
    accepted_answers: ["Moselle", "Seille"],
    display_answer: "Moselle",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Perpignan ?",
    accepted_answers: ["Têt"],
    display_answer: "Têt",
    difficulty: 5,
  },
  {
    text: "Quel fleuve traverse la ville de Montpellier ?",
    accepted_answers: ["Lez"],
    display_answer: "Lez",
    difficulty: 5,
  },
  {
    text: "Quel est le département le plus peuplé de France ?",
    accepted_answers: ["Nord", "59"],
    display_answer: "Nord",
    difficulty: 5,
  },
  {
    text: "Quel est le deuxième département le plus peuplé de France ?",
    accepted_answers: ["Bouches-du-Rhône", "Bouches du Rhone", "13"],
    display_answer: "Bouches-du-Rhône",
    difficulty: 5,
  },
  {
    text: "Quel département a le plus de communes ?",
    accepted_answers: ["Pas-de-Calais", "Pas de Calais", "62"],
    display_answer: "Pas-de-Calais",
    difficulty: 5,
  },
  {
    text: "Quel département métropolitain a la plus faible densité de population ?",
    accepted_answers: ["Lozère", "48"],
    display_answer: "Lozère",
    difficulty: 5,
  },
  {
    text: "Quel département métropolitain a la plus forte densité de population ?",
    accepted_answers: ["Paris", "75"],
    display_answer: "Paris",
    difficulty: 5,
  },
  {
    text: "Quel département borde le plus d'autres départements (8 voisins) ?",
    accepted_answers: ["Cher", "18"],
    display_answer: "Cher",
    difficulty: 5,
  },
  {
    text: "Dans quel département se trouve le col du Tourmalet ?",
    accepted_answers: ["Hautes-Pyrénées", "Hautes Pyrenees", "65"],
    display_answer: "Hautes-Pyrénées",
    difficulty: 5,
  },
  {
    text: "Dans quel département se trouve le Mont Ventoux ?",
    accepted_answers: ["Vaucluse", "84"],
    display_answer: "Vaucluse",
    difficulty: 5,
  },
  {
    text: "Dans quel département se trouve le Puy de Dôme ?",
    accepted_answers: ["Puy-de-Dôme", "Puy de Dome", "63"],
    display_answer: "Puy-de-Dôme",
    difficulty: 5,
  },
  {
    text: "Quelle sous-préfecture du Finistère se trouve à l'extrémité ouest ?",
    accepted_answers: ["Brest"],
    display_answer: "Brest",
    difficulty: 5,
  },
  {
    text: "Dans quel département se trouve le viaduc de Millau ?",
    accepted_answers: ["Aveyron", "12"],
    display_answer: "Aveyron",
    difficulty: 5,
  },
  {
    text: "Quelle est la sous-préfecture de la Creuse ?",
    accepted_answers: ["Aubusson"],
    display_answer: "Aubusson",
    difficulty: 5,
  },
  {
    text: "Dans quel département se trouve le Mont-Saint-Michel ?",
    accepted_answers: ["Manche", "50"],
    display_answer: "Manche",
    difficulty: 5,
  },
  {
    text: "Quel département est entièrement enclavé dans un autre département ?",
    accepted_answers: ["Territoire de Belfort", "90"],
    display_answer: "Territoire de Belfort",
    difficulty: 5,
  },
  {
    text: "Quels départements composent la Corse ?",
    accepted_answers: ["Corse-du-Sud", "Haute-Corse", "2A", "2B"],
    display_answer: "Corse-du-Sud et Haute-Corse",
    difficulty: 5,
  },
  {
    text: "Dans quelle région se trouve le département des Côtes-d'Armor ?",
    accepted_answers: ["Bretagne"],
    display_answer: "Bretagne",
    difficulty: 5,
  },
  {
    text: "Dans quelle région se trouve le département du Cantal ?",
    accepted_answers: ["Auvergne-Rhône-Alpes"],
    display_answer: "Auvergne-Rhône-Alpes",
    difficulty: 5,
  },
  {
    text: "Quel fleuve forme une partie de la frontière entre la France et l'Allemagne ?",
    accepted_answers: ["Rhin"],
    display_answer: "Rhin",
    difficulty: 5,
  },
  {
    text: "Quel fleuve forme une partie de la frontière entre la France et l'Espagne ?",
    accepted_answers: ["Pyrénées", "Pyrenees"],
    display_answer: "Les Pyrénées",
    difficulty: 5,
  },
  {
    text: "Dans quel département se trouve la ville de Saint-Malo ?",
    accepted_answers: ["Ille-et-Vilaine", "35"],
    display_answer: "Ille-et-Vilaine",
    difficulty: 5,
  },

  // Difficulty 6 — expert / joker pool
  {
    text: "Quelle est la sous-préfecture du département de la Lozère ?",
    accepted_answers: ["Florac"],
    display_answer: "Florac",
    difficulty: 6,
  },
  {
    text: "Quel est le plus haut sommet du Massif central ?",
    accepted_answers: ["Puy de Sancy", "Sancy"],
    display_answer: "Puy de Sancy",
    difficulty: 6,
  },
  {
    text: "Quel fleuve traverse la ville de Guéret ?",
    accepted_answers: ["Creuse"],
    display_answer: "Creuse",
    difficulty: 6,
  },
  {
    text: "Quel fleuve traverse la ville de Privas ?",
    accepted_answers: ["Ardèche", "Ardeche"],
    display_answer: "Ardèche",
    difficulty: 6,
  },
  {
    text: "Quel fleuve traverse la ville de Aurillac ?",
    accepted_answers: ["Cère", "Cere", "Jordanne"],
    display_answer: "Cère",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve la ville de Vervins ?",
    accepted_answers: ["Aisne", "02"],
    display_answer: "Aisne",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve la ville de Nyons ?",
    accepted_answers: ["Drôme", "Drome", "26"],
    display_answer: "Drôme",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve la ville de Largentière ?",
    accepted_answers: ["Ardèche", "Ardeche", "07"],
    display_answer: "Ardèche",
    difficulty: 6,
  },
  {
    text: "Quelle est la préfecture du département le moins peuplé de France métropolitaine ?",
    accepted_answers: ["Mende"],
    display_answer: "Mende",
    difficulty: 6,
  },
  {
    text: "Combien de départements composent la France métropolitaine ?",
    accepted_answers: ["96", "quatre-vingt-seize"],
    display_answer: "96",
    difficulty: 6,
  },
  {
    text: "Quel département a pour préfecture Foix ?",
    accepted_answers: ["Ariège", "Ariege", "09"],
    display_answer: "Ariège",
    difficulty: 6,
  },
  {
    text: "Quel département a pour préfecture Bar-le-Duc ?",
    accepted_answers: ["Meuse", "55"],
    display_answer: "Meuse",
    difficulty: 6,
  },
  {
    text: "Quel département a pour préfecture Chaumont ?",
    accepted_answers: ["Haute-Marne", "Haute Marne", "52"],
    display_answer: "Haute-Marne",
    difficulty: 6,
  },
  {
    text: "Dans quel estuaire se rejettent la Garonne et la Dordogne ?",
    accepted_answers: ["Gironde", "estuaire de la Gironde"],
    display_answer: "L'estuaire de la Gironde",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouvent les gorges du Verdon ?",
    accepted_answers: ["Alpes-de-Haute-Provence", "Var", "04", "83"],
    display_answer: "Alpes-de-Haute-Provence / Var",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve le lac du Salagou ?",
    accepted_answers: ["Hérault", "Herault", "34"],
    display_answer: "Hérault",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve le Parc national des Cévennes ?",
    accepted_answers: ["Lozère", "Gard", "48", "30"],
    display_answer: "Lozère / Gard",
    difficulty: 6,
  },
  {
    text: "Quel département est traversé par la ligne du Méridien de Greenwich ?",
    accepted_answers: ["Ain", "01"],
    display_answer: "Ain",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve le cirque de Gavarnie ?",
    accepted_answers: ["Hautes-Pyrénées", "Hautes Pyrenees", "65"],
    display_answer: "Hautes-Pyrénées",
    difficulty: 6,
  },
  {
    text: "Quel fleuve se jette dans la Manche au Havre ?",
    accepted_answers: ["Seine"],
    display_answer: "Seine",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve la ville de Montdidier ?",
    accepted_answers: ["Somme", "80"],
    display_answer: "Somme",
    difficulty: 6,
  },
  {
    text: "Dans quel département se trouve la ville de Clamecy ?",
    accepted_answers: ["Nièvre", "Nievre", "58"],
    display_answer: "Nièvre",
    difficulty: 6,
  },
  {
    text: "Quel fleuve traverse la ville de Épinal ?",
    accepted_answers: ["Moselle"],
    display_answer: "Moselle",
    difficulty: 6,
  },
  {
    text: "Quel fleuve traverse la ville de Nevers ?",
    accepted_answers: ["Loire"],
    display_answer: "Loire",
    difficulty: 6,
  },
  {
    text: "Quel fleuve traverse la ville de Auxerre ?",
    accepted_answers: ["Yonne"],
    display_answer: "Yonne",
    difficulty: 6,
  },
  {
    text: "Quel est le numéro du département des Hautes-Pyrénées ?",
    accepted_answers: ["65"],
    display_answer: "65",
    difficulty: 6,
  },
  {
    text: "Quel est le numéro du département de la Haute-Loire ?",
    accepted_answers: ["43"],
    display_answer: "43",
    difficulty: 6,
  },
  {
    text: "Quel est le numéro du département de l'Indre ?",
    accepted_answers: ["36"],
    display_answer: "36",
    difficulty: 6,
  },
  {
    text: "Quelle région administrative regroupe les départements du Rhône et de l'Ain ?",
    accepted_answers: ["Auvergne-Rhône-Alpes", "Auvergne Rhone Alpes"],
    display_answer: "Auvergne-Rhône-Alpes",
    difficulty: 6,
  },
  {
    text: "Quelle région administrative regroupe les départements du Finistère et du Morbihan ?",
    accepted_answers: ["Bretagne"],
    display_answer: "Bretagne",
    difficulty: 6,
  },
];
